---
name: App-ZofCMS-Plugin-Doctypes
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: include DOCTYPEs in your pages without remembering how to spell them
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::ZofCMS: 0.0105
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::Doctypes:
    file: lib/App/ZofCMS/Plugin/Doctypes.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
